### ISSUE TITLE
Example fails with OperationStopped: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by eabase** [chrisseroka/ps-menu#17] opened 2023-12-09 20:00 UTC
Running the 1st example, give the error:
```powershell
# menu @("option 1", "option 2", "option 3")
> option 1
  option 2
  option 3
OperationStopped: Index was outside the bounds of the array.
option 1
```

**Comment by eabase** [comment] 2023-12-09 22:28
There is a bug in your code, here:
https://github.com/chrisseroka/ps-menu/blob/master/ps-menu.psm1#L4

It is using `-le` instead of `-lt`. It should read:
```
for ($i = 0; $i -lt $l;$i++) {
```

**Comment by eabase** [comment] 2023-12-09 22:36
It should be noted also to beware of masking of aliases. 
I had to rewrite:
```powershell
# Careful: 
#	"cd"  is masked by OS alias, use "Set-Location"
#	"dir" is masked by OS alias, use "Get-ChildItem"
#	"iex" is masked by OS alias, use "Invoke-Expression"

function cdx {
	$A = Get-ChildItem -Dir
	if ($A) { 
		$dir = Menu @($A)
		Set-Location $dir
	} else {
		Write-Host -f Red "No Directory here!" 
	}
}

```

**Comment by chrisseroka** [comment] 2024-03-03 21:30
> There is a bug in your code, here: https://github.com/chrisseroka/ps-menu/blob/master/ps-menu.psm1#L4
> 
> It is using `-le` instead of `-lt`. It should read:
> 
> ```
> for ($i = 0; $i -lt $l;$i++) {
> ```

`-lt`  (lower than) is used on purpose as array is indexed from 0

**Comment by chrisseroka** [comment] 2024-03-03 21:31
Closing as the issue is not reproducible

**Closed as completed by chrisseroka** 2024-03-03 21:31 UTC
